name: DEV Merge Rule

on: 
  push:
    branches: 
    - DEV

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to DEV not coming from main/master or feature
        if: github.base_ref == 'DEV' && (github.head_ref != 'main' && github.head_ref != 'master' && !contains(github.head_ref, 'feature/'))
        run: |
          echo "Error: You can only merge main/master and feature/* branches to DEV"
          exit 1
