name: DEV Merge Rule

on: 
  pull_request:
    branches: 
    - DEV

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to DEV not coming from main/master or feature
        if: github.base_ref == 'DEV' && (github.head_ref != 'main' && github.head_ref != 'master' && !contains(github.head_ref, 'feature/'))
        run: |
          echo "Error: You can only merge main/master and feature/* branches to DEV"
          exit 1
#
name: TEST Merge Rule

on: 
  pull_request:
    branches: 
    - TEST

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to TEST not coming from DEV
        if: github.base_ref == 'TEST' && github.head_ref != 'DEV'
        run: |
          echo "Error: You can only merge DEV to TEST"
          exit 1
#
name: UAT Merge Rule

on: 
  pull_request:
    branches: 
    - UAT

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to UAT not coming from TEST
        if: github.base_ref == 'UAT' && github.head_ref != 'TEST'
        run: |
          echo "Error: You can only merge TEST to UAT"
          exit 1
#
name: PROD Merge Rule

on: 
  pull_request:
    branches: 
    - PROD

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to PROD not coming from UAT or hotfix
        if: github.base_ref == 'PROD' && (github.head_ref != 'UAT' && !contains(github.head_ref, 'hotfix/'))
        run: |
          echo "Error: You can only merge UAT and hotfix/* branches to PROD"
          exit 1
#
name: Master and Main Merge Rule

on: 
  pull_request:
    branches: 
    - main
    - master

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge to main/master not coming from PROD
        if: (github.base_ref == 'main' || github.base_ref == 'master') && github.head_ref != 'PROD'
        run: |
          echo "Error: You can only merge PROD to main/master"
          exit 1
#
name: Feature Merge Rule

on: 
  pull_request:
    branches: 
    - feature/*

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block merge from feature not coming from feature
        if: contains(github.base_ref, 'feature/') && !contains(github.head_ref, 'feature/')
        run: |
          echo "Error: You can only merge feature branches to feature branches"
          exit 1
#
name: Hotfix Merge Rule

on: 
  pull_request:
    branches: 
    - hotfix/*

jobs:
  validate-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Block any merge to hotfix branches
        if: contains(github.base_ref, 'hotfix/') || contains(github.base_ref, 'hotfix')
        run: |
          echo "Error: You cannot merge into any hotfix branches"
          exit 1
